version: "3.8"
services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssqlserver
    restart: always
    hostname: mssql
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    # Express:
    volumes:
      - mssqlvolume:/var/opt/mssql/data # thư mục lưu DB
      - ./bk:/var/opt/mssql/backup      # thư  mục chứa file backup
    ports:
      - "5434:1433"
      
volumes:
    mssqlvolume:
  